name: ci

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: echo "buildingg code"
      - run: echo "testing code"
      - run: ls -la
      - run: echo "hello nikhil" >> test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: myartifact
          path: test.txt
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [checkout,build]
    environment: dev
    steps:
      - run: ls -la
      - uses: actions/download-artifact@v4
        with:
          name: myartifact
      - run: cat test.txt
      - run: echo "Using DEV secret = ${{ secrets.devsecret }}"
  deploy-test:
    runs-on: ubuntu-latest
    if: github.ref_name == 'test'
    environment: test
    needs: [checkout,build,deploy-dev]
    steps:
      - run: ls -la
      - uses: actions/download-artifact@v4
        with:
          name: myartifact
      - run: cat test.txt
      - run: echo "Using TEST secret = ${{ secrets.testsecret }}"
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: prod
    needs: [checkout,build,deploy-dev,deploy-test]
    steps:
      - run: ls -la
      - uses: actions/download-artifact@v4
        with:
          name: myartifact
      - run: cat test.txt
      - run: echo "Using PROD secret = ${{ secrets.prodsecret }}"


    
