name: ci

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: echo "buildingg code"
      - run: echo "testing code"
      - run: ls -la
      - run: echo "hello nikhil" >> test.txt
      - uses: actions/upload-artifacts@v4
        with:
          name: myartifact
          path: test.txt
  deploy:
    runs-on: ubuntu-latest
    needs: [checkout,build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myartifact
      - run: cat test.txt


    
